USE NUR;
DROP TABLE IF EXISTS HPUSER;
CREATE TABLE IF NOT EXISTS HPUSER (
  GID varchar(32) NOT NULL PRIMARY KEY,
  DOMAINUSERNAME varchar(30) NOT NULL,
  EMPLOYEEID int(10),
  FIRSTNAME varchar(30),
  LASTNAME varchar(30),
  NAME varchar(30),
  EMPLOYEEEMAIL varchar(30),
  USERSTATUS varchar(10),
  LASTLOGINDATE datetime,
  CREATEDDATE datetime,
  LASTMODIFYDATE datetime,
  CREATEDBY varchar(32),
  LASTMODIFIEDBY varchar(32)
)